### ISSUE TITLE
Item Duplicating - Roster Editor

### ISSUE THREAD

**Issue by cartag** [BattleScribe/Release#91]
I have a unit that starts as one primary category (Behemoth) and can be turned into another (Leader) if it takes a certain upgrade (Anointed riding it). If a category gets added then removed from a unit while it is already changed, it causes a duplicate item to appear. I'll screenshot the process. There seems to be issues with changed primary category processing still. 

![image](https://user-images.githubusercontent.com/4388344/66793787-2562b900-eebc-11e9-87b9-dc7bc754996d.png)

![image](https://user-images.githubusercontent.com/4388344/66793794-2f84b780-eebc-11e9-9651-be014e0aa9bb.png)

![image](https://user-images.githubusercontent.com/4388344/66793806-390e1f80-eebc-11e9-9605-a0b2dc7162fc.png)

![image](https://user-images.githubusercontent.com/4388344/66793817-43301e00-eebc-11e9-90f8-1ecdbad04b15.png)

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.13.142
Android: 2.03.19.328
iOS: 2.03.11.147

**Comment by cartag** [comment]
Not fixed in latest version. New roster. Only seems to duplicate when any subfaction is active. 
![image](https://user-images.githubusercontent.com/4388344/77372727-f59dc400-6d2b-11ea-9e75-afffd8ba8536.png)

**Comment by cartag** [comment]
Steps to duplicate: New Slaves to Darkness roster. Change allegiance to anything other than StD. Change back to StD, then add subfaction. Duplication occurs.

**Comment by cartag** [comment]
Issue persists in new beta also, but is not exclusive to it. 

![image](https://user-images.githubusercontent.com/4388344/77492409-1e928780-6e06-11ea-8c66-47761c320315.png)
